services:
  db:
    image: mysql:8.0.39
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: map-reservation
    ports:
      - "3312:3306"
  redis:
    image: redis:7.4.0
    restart: always
    ports:
      - "6380:6379"
