### CSRF 발급
GET http://localhost:8080/api/csrf-token

> {%
    client.global.set("csrfToken", response.body.csrfToken.token)
%}

### 회원가입
POST http://localhost:8080/api/members
Content-Type: application/json
X-CSRF-TOKEN: {{csrfToken}}

{
  "email": "abc@gmail.com",
  "password": "12345"
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded
X-CSRF-TOKEN: {{csrfToken}}

username = abc@gmail.com &
password = 12345
