name: build-push-deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_SERVER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/map-reservation-api-server:${{ github.sha }}
    steps:
      # build, push steps
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker images
        uses: docker/build-push-action@v5.2.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.API_SERVER_IMAGE_NAME }}

      # deploy steps
      - name: Copy script, docker compose files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }} # 퍼블릭 ip
          port: ${{ secrets.SERVER_PORT }} # 포트 번호
          username: ${{ secrets.SERVER_USERNAME }} # 계정명
          key: ${{ secrets.SERVER_KEY }} # raw contents of private key
          source: "docker-compose-prod.yml,scripts/prod-run.sh"
          target: "map-reservation"

      - name: Docker compose up
        uses: appleboy/ssh-action@v1.0.3
        env:
          APISERVER_IMAGE_NAME: ${{ env.APISERVER_IMAGE_NAME }}
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: APISERVER_IMAGE_NAME
          script: |
            cd map-reservation
            sh scripts/prod-run.sh
